[package]
name = "mismall" #short for "make it small"
version = "1.0.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
rand = "0.9.2"
serde = { version = "1.0.219", features = ["derive"] }
